module.exports = {
	SIGNATURE_VERIFICATION_LEVEL1: '1',
	SIGNATURE_VERIFICATION_LEVEL2: '2',

	ORDER_CREATION_REQUEST: 'ORDER_CREATION_REQUEST',
	ORDER_STATUS_REQUEST: 'ORDER_STATUS_REQUEST',

	PAYMENT_FAIL_ERROR_MESSAGE: 'Payment Failed',
	PAYMENT_FAIL_ERROR_CODE: '500',

	PAYMENT_SUCCESS_STATUS: 'Payment Success',

	CREATE_MERCHANT_VERIFICATION_TOKEN_REQUEST: 'CREATE_MERCHANT_VERIFICATION_TOKEN_REQUEST',

    PLATFORM: 'WEB',

    RESPONSE_TYPE_ERROR: 'error',

    VALIDATION_TYPE_REQUIRED: 'Required',
    VALIDATION_TYPE_INVALID_TYPE: 'InValid Type',

    SUCCESS_SIGNATURE_VERIFICATION: 'SUCCESS_SIGNATURE_VERIFICATION',
    ERROR_SIGNATURE_VERIFICATION: 'ERROR_SIGNATURE_VERIFICATION',
};
